### PR TITLE
gender test

### PR DESCRIPTION
**Pull request by Ananthavijay**
This file tests the gender of a person with their first name and gives the probability. If it works just add it . :smile:

### CODE REVIEW

**Comment by gabru-md** [comment]
Let me see.
If it works fine then it will be merged by the end of the day

**Comment by Ananthavijay** [comment]
Thanks @gabru-md

**Comment by Ananthavijay** [comment]
no need of this

**Comment by xeon-zolt** [comment]
Was thinking why bridge requires gender test

**Pull request closed without merging**
